#ifndef CONSTANTS
#define CONSTANTS

#define DATA_FILE_NAME "movieCollection.dat"

#define MAX_MOVIE_COUNT 100
#define MAX_MOVIE_TITLE_LENGTH 30
#define MAX_MOVIE_ID_LENGTH 12
#define MAX_MOVIE_QUANTITY_DIGITS 8
#define MAX_MOVIE_PRICE_DIGITS 8

#endif